-- Run this in Supabase SQL Editor

create extension if not exists pgcrypto;

create type public.post_status as enum ('draft', 'published');

create table if not exists public.posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid not null references auth.users (id) on delete cascade default auth.uid(),
  sequence integer generated by default as identity unique,
  slug text not null unique,
  title text not null,
  body_html text not null,
  status public.post_status not null default 'draft',
  featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create index if not exists idx_posts_status_created_at on public.posts(status, created_at desc);
create index if not exists idx_posts_author_id on public.posts(author_id);
create index if not exists idx_posts_slug on public.posts(slug);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_posts_updated_at on public.posts;
create trigger trg_posts_updated_at
before update on public.posts
for each row
execute function public.set_updated_at();

alter table public.posts enable row level security;

-- Public visitors can only read published posts.
drop policy if exists "published posts are public" on public.posts;
create policy "published posts are public"
on public.posts
for select
to anon, authenticated
using (status = 'published');

-- Authenticated users can read their own drafts and published posts.
drop policy if exists "users can read own posts" on public.posts;
create policy "users can read own posts"
on public.posts
for select
to authenticated
using (author_id = auth.uid());

-- Only authenticated users can write, and only as themselves.
drop policy if exists "users can insert own posts" on public.posts;
create policy "users can insert own posts"
on public.posts
for insert
to authenticated
with check (author_id = auth.uid());

drop policy if exists "users can update own posts" on public.posts;
create policy "users can update own posts"
on public.posts
for update
to authenticated
using (author_id = auth.uid())
with check (author_id = auth.uid());

drop policy if exists "users can delete own posts" on public.posts;
create policy "users can delete own posts"
on public.posts
for delete
to authenticated
using (author_id = auth.uid());
